#!/bin/bash
#SBATCH --job-name=lmp_gpu_intel
#SBATCH --output=lmp_gpu_intel.out
#SBATCH --error=lmp_gpu_intel.err
#SBATCH --time=34:00:00
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=34
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:4

module purge
module load intel-compilers/2022.2.1
module load impi/2021.7.1-intel-compilers-2022.2.1
module load Python/3.10.8-GCCcore-12.2.0
module load CUDA/11.4.1

export LD_LIBRARY_PATH=$(echo "$LD_LIBRARY_PATH" \
    | tr ':' '\n' \
    | grep -v 'OpenSSL/1.1/lib' \
    | paste -sd ':' -)

echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"

export OMP_NUM_THREADS=1
export I_MPI_FABRICS=shm:ofi
export I_MPI_HYDRA_BOOTSTRAP=ssh

export CUPY_DUMP_CUDA_SOURCE_ON_ERROR=1
export CUPY_CACHE_SAVE_CUDA_SOURCE=1
export CUPY_DISABLE_JITIFY_CACHE=1
export CUPY_COMPILE_WITH_PTX=1    

source ~/env_lpc3d_lammps_gpu/bin/activate

cd /ceph/hpc/home/euhassanl/eau_gpu/4

if [ -n "$CUDA_VISIBLE_DEVICES" ]; then
    NGPU=$(echo "$CUDA_VISIBLE_DEVICES" | tr ',' '\n' | wc -l)
else
    NGPU=0
fi

export LPC3D_NUM_GPUS=$NGPU
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
echo "LPC3D_NUM_GPUS=$LPC3D_NUM_GPUS"

mpirun -np 34 python3 LAMMPS-LPC3D.py -i lattice_gas.inpt

